export const SERVER_ERROR = 'SERVER_ERROR';
export const INVALID_PARAM = 'INVALID_PARAM';
export const INVALID_DATA = 'INVALID_DATA';
export const UNAUTHORIZED = 'UNAUTHORIZED';
export const RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND';
export const MONGO_TRANSACTION_ERROR = 'MONGO_TRANSACTION_ERROR';
export const PERMISSION_DENIED = 'PERMISSION_DENIED';

export default {
    SERVER_ERROR,
    INVALID_PARAM,
    INVALID_DATA,
    UNAUTHORIZED,
    RESOURCE_NOT_FOUND,
    MONGO_TRANSACTION_ERROR,
    PERMISSION_DENIED,
};
